name: Integration

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v1
    - uses: actions/heroku@1.0.0

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/les-projets-cagnottes/slack-events-catcher/slack-events-catcher:latest
    
    - name: Login to Registry
      run: docker login docker.pkg.github.com -u thomah -p ${{secrets.GITHUB_TOKEN}}

    - name: Publish to Registry
      run: docker push docker.pkg.github.com/les-projets-cagnottes/slack-events-catcher/slack-events-catcher:latest
      
    - name: Build the Docker image
      run: docker tag docker.pkg.github.com/les-projets-cagnottes/slack-events-catcher/slack-events-catcher:latest registry.heroku.com/lpc-slack/web
    
    - name: Get Heroku Tools
      run: wget -qO- https://toolbelt.heroku.com/install.sh | sh

    - name: Login to Heroku Registry
      run: echo "${{secrets.HEROKU_PASSWORD}}" | docker login -u "${{secrets.HEROKU_USERNAME}}" --password-stdin registry.heroku.com

    - name: Login to Heroku API
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_PASSWORD}}

    - name: Publish to Heroku Registry
      run: docker push registry.heroku.com/lpc-slack/web

    - name: Release Heroku app
      run: heroku container:release web --app lpc-slack
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_PASSWORD}}
