name: Production Publish

on:
  push:
    tags:
    - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v1
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true

    - uses: horochx/deploy-via-scp@1.0.1
      with:
        local: .
        remote: ${{ secrets.PRODUCTION_PATH }}
        host: ${{ secrets.PRODUCTION_HOST }}
        port: ${{ secrets.PRODUCTION_PORT }}
        user: ${{ secrets.PRODUCTION_USER }}
        key: ${{ secrets.PRODUCTION_KEY }}