name: Release

on:
  release:
    types: [created]

jobs:

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #         registry-url: https://npm.pkg.github.com/
  #         scope: '@les-projets-cagnottes'
  #     - run: npm ci
  #     - run: npm config set registry https://npm.pkg.github.com/
  #     - run: echo '//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}' > .npmrc
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  # publish-npm:
  #   needs: publish-gpr
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}


  deploy-prod:
    # needs: publish-npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: npm ci
    - uses: horochx/deploy-via-scp@v1.0.1
      with:
        local: .
        remote: ${{ secrets.PRODUCTION_PATH }}
        host: ${{ secrets.PRODUCTION_HOST }}
        port: ${{ secrets.PRODUCTION_PORT }}
        user: ${{ secrets.PRODUCTION_USER }}
        key: ${{ secrets.PRODUCTION_KEY }}