name: Release

on:
  release:
    types: [created]

jobs:

#   publish-gpr:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#           registry-url: https://npm.pkg.github.com/
#           scope: '@les-projets-cagnottes'
#       - run: npm ci
#       - run: npm config set registry https://npm.pkg.github.com/
#       - run: echo '//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}' > .npmrc
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

#   publish-npm:
#     needs: publish-gpr
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#           registry-url: https://registry.npmjs.org/
#       - run: npm ci
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-docker:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/les-projets-cagnottes/slack-events-catcher/slack-events-catcher:latest

    - name: Login to Registry
      run: docker login docker.pkg.github.com -u thomah -p ${{secrets.GITHUB_TOKEN}}

    - name: Publish to Registry
      run: docker push docker.pkg.github.com/les-projets-cagnottes/slack-events-catcher/slack-events-catcher:latest

  deploy-production:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Copy content recursively to production
      uses: appleboy/scp-action@v0.0.7
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USER }}
        key : ${{ secrets.PRODUCTION_KEY }}
        port: ${{ secrets.PRODUCTION_PORT }}
        source: "."
        target: /opt/les-projets-cagnottes/slack-events-catcher/deployment
        rm: true
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.0.6
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USER }}
        key : ${{ secrets.PRODUCTION_KEY }}
        port: ${{ secrets.PRODUCTION_PORT }}
        script: (sudo chmod 755 /opt/les-projets-cagnottes/slack-events-catcher/deployment/bin/deploy.sh) && (nohup /opt/les-projets-cagnottes/slack-events-catcher/deployment/bin/deploy.sh ${{ steps.get_version.outputs.VERSION }} &>  /opt/les-projets-cagnottes/slack-events-catcher/deployment/bin/console.log < /dev/null &) && exit 0
